# Generated by Django 6.0.2 on 2026-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='synced_lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
