# Generated by Django 5.2.8 on 2026-04-04 07:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_playlist_song_order(apps, schema_editor):
    PlaylistSong = apps.get_model('core', 'PlaylistSong')
    playlist_ids = (
        PlaylistSong.objects.order_by()
        .values_list('playlist_id', flat=True)
        .distinct()
    )

    for playlist_id in playlist_ids:
        entries = PlaylistSong.objects.filter(playlist_id=playlist_id).order_by('id')
        for index, entry in enumerate(entries, start=1):
            PlaylistSong.objects.filter(pk=entry.pk).update(order=index)


def create_share_links_for_existing_playlists(apps, schema_editor):
    Playlist = apps.get_model('core', 'Playlist')
    ShareLink = apps.get_model('core', 'ShareLink')

    for playlist in Playlist.objects.all():
        ShareLink.objects.get_or_create(playlist=playlist)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_synced_lyrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE core_playlist_songs ADD COLUMN "order" integer NOT NULL DEFAULT 1;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PlaylistSong',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order', models.PositiveIntegerField(default=1)),
                        (
                            'playlist',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='playlist_songs',
                                to='core.playlist',
                            ),
                        ),
                        (
                            'song',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='playlist_entries',
                                to='core.song',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'core_playlist_songs',
                        'ordering': ['order'],
                        'unique_together': {('playlist', 'song')},
                    },
                ),
                migrations.AlterField(
                    model_name='playlist',
                    name='songs',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='playlists',
                        through='core.PlaylistSong',
                        to='core.song',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.generate_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='share_links',
                        to='core.playlist',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'added_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_playlist_collaborations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collaborators',
                        to='core.playlist',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_collaborations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['playlist', 'role'], name='core_playli_playlis_f4304d_idx')],
                'unique_together': {('playlist', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='core.playlist',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['playlist', 'created_at'], name='core_playli_playlis_cfc175_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaylistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='likes',
                        to='core.playlist',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_likes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('playlist', 'user')},
            },
        ),
        migrations.RunPython(populate_playlist_song_order, migrations.RunPython.noop),
        migrations.RunPython(create_share_links_for_existing_playlists, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='playlistsong',
            index=models.Index(fields=['playlist', 'order'], name='core_playli_playlis_050a9f_idx'),
        ),
    ]
